@startuml deployment
node ClientDevice {
[Kiosk UI]
[Operator Panel UI]
[Waiting Room Display]
[Admin Dashboard]
}


node Server {
component TicketService
component OperatorService
component ReportService
component WebSocketGateway
component ConfigAPI
}


node Database {
[QMS_DB]
}


[Kiosk UI] --> TicketService
[Operator Panel UI] --> OperatorService
[Admin Dashboard] --> ConfigAPI
[Waiting Room Display] --> WebSocketGateway


TicketService --> QMS_DB
OperatorService --> QMS_DB
ReportService --> QMS_DB
WebSocketGateway --> QMS_DB
@enduml