@startuml use_case_qms
left to right direction
actor Client
actor Operator
actor Admin


(Client) --> (Generate Ticket)
(Client) --> (Wait in Queue)
(Operator) --> (View Next Ticket)
(Operator) --> (Start Transaction)
(Operator) --> (End Transaction)
(Operator) --> (Change Status: Lunch, Break, Personal)
(Admin) --> (Configure Areas and Services)
(Admin) --> (Manage Operators)
(Admin) --> (View Reports)
(Operator) --> (Transfer Ticket)
@enduml